### PR TITLE
OpenTracing instrumentation with Zipkin impl

### PR DESCRIPTION
**Pull request by pavolloffay**
This removes Zipkin specific instrumentation and instead uses OpenTracing vendor neutral instrumentation API to describe application behavior. As a backed it uses Zipkin implementation. This allows O(1) change between tracing implementations (Zipkin, Hawkular APM, Jaeger).  

This PR uses OpenTracing framework integrations which automatically create tracing data for given framework:
* `io.opentracing.contrib:opentracing-spring-web-autoconfigure` [repo](https://github.com/opentracing-contrib/java-spring-web): It automatically registers tracing filter and spring interceptor to trace all server requests (authenticated, no URL mapping..)
* `io.github.openfeign:feign-opentracing` [repo](https://github.com/OpenFeign/feign-opentracing): It instruments all Feign compatible clients. It creates clien spans for every outgoing request.

Do not merge yet!

### CODE REVIEW

**Comment by pavolloffay** [comment]
@rafabene PR rebased. I had to update feign client to `9.4.0` which has changed `groupId` to `io.github.openfeign`

**Comment by rafabene** [comment]
Shouldn't this also be applied to https://github.com/redhat-helloworld-msa/api-gateway ?

**Comment by pavolloffay** [comment]
> Shouldn't this also be applied to https://github.com/redhat-helloworld-msa/api-gateway ? 

What change do you exactly mean?

If you like and approve these changes regarding instrumentation I will update all services ('api-gateway', 'hola', 'aloha'..) to use OpenTracing with Zipkin. Do not merge this yet!

**Comment by rafabene** [comment]
I mean change from Brave to OpenTracing instrumentation with Zipkin impl

**Comment by pavolloffay** [comment]
So @rafabene do you accept this change? If you say yes I will open similar PR's to other services and we can run it and see it in action.

**Comment by rafabene** [comment]
Yes. I accept this change but I won't merge until I have the other PRs so I can do it atomically.

**Comment by pavolloffay** [comment]
Great :100: I will submit them on Monday. Thanks!

**Pull request merged**
